import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "sonner";
import { AuthProvider } from '../context/AuthContext';


export const metadata = {
  title: "Crud empleados Free",
  description: "Generated by create next app",
};
const inter = Inter({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
         <AuthProvider>
         <Toaster   />
         {children}
         </AuthProvider>
        
      </body>
    </html>
  );
}
